# src/docker-compose.yml
# Docker Compose configuration for SIP Phone API with PJSIP

version: '3.8'

services:
  sip-phone-api:
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # REST API
      - "5060:5060/udp"  # SIP
    volumes:
      - ../src/data:/app/data
      - ../src/logs:/app/logs
      - ../src/config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG  # Set to DEBUG for development
      - PJSIP_LOG_LEVEL=5  # Maximum PJSIP logging (0-6, where 6 is most verbose)
    restart: unless-stopped
