version: '3.8'

services:
  api:
    build:
      target: development
    environment:
      - DEBUG=1
      - MOCK_HARDWARE=true
      - DEBUG_DTMF=true
      - DEBUG_AUDIO=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app:ro  # Mount source code for development
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "sip_phone"]
    ports:
      - "5678:5678"  # Debug port
